// NAVIGATION ACTION
export const TOGGLE_MENU_DRAWER = "TOGGLE-MENU-DRAWER";
export const OPEN_MENU_DRAWER = "OPEN-MENU-DRAWER";
export const OPEN_MENU_DRAWER_FOR_SEARCH = "OPEN-MENU-DRAWER-FOR-SEARCH";
// NAVIGATION ACTION
